### ISSUE TITLE
Large 12 million payout amounting to more than my profit in the previous year

### ISSUE THREAD

**Issue by longtomjr** [mattkimber/openttd_villages_is_villages#2]
I were floating a lot of money to try and see how the tax and dividend payouts will play out over the length of a game. This is using JGR's patch pack version 35.1. I will attach the save I have the closest to that payout. It is unfortunately almost 2 years after it. (Sorry, I only realized that this is an anomaly after waiting another 2 years).

There is a bunch of newGRFs loaded, so this might be a cause outside of the gamescript. I will post an update when and if I can reproduce it at a later date.

![Flunbridge Transport, 1954-10-01#1](https://user-images.githubusercontent.com/3615508/88966520-bae50300-d2ac-11ea-86e3-33459d284dbe.png)
![Flunbridge Transport, 1954-10-01#2](https://user-images.githubusercontent.com/3615508/88966524-bc163000-d2ac-11ea-858f-f0d522d24b4d.png)

Save closest to the payout
[Large_Payout.sav.zip](https://github.com/mattkimber/openttd_villages_is_villages/files/5003450/Large_Payout.sav.zip)

I have a save 3 years before the payout that I can run through and see if I can reproduce it.

**Comment by mattkimber** [comment]
Is this with dividends enabled? If so, that's a deliberate mechanic - the dividends are based on surplus **cash** (not profits). The intention is to prevent players building small networks and building up huge cash piles by sitting back and doing nothing, particularly in multiplayer games. With a large cash pile this can be vastly in excess of profit, although eventually it will stabilise as the dividends wipe out the excess cash. Note that dividends will always leave you with a couple of years running costs - if you use a trainset with higher costs in relation to profits you'll see the dividends take a much smaller chunk.

If you're getting that with corporation tax alone enabled, then there is a bug; tax is based solely on profit.

**Comment by longtomjr** [comment]
The news ticker showed dividends payed out as 1% and iirc around 850k gbp. This is only in my 3rd year (started in 1950). I will load my save from 1951 and check if I can reproduce it this weekend.

**Comment by mattkimber** [comment]
The amount displayed in news is the same as the amount sent to GSChangeBankBalance (l94-95 of company.nut), so what you see in the news article is what it asked OpenTTD to take.

The graph does look about normal for some of the chunkier dividends paid out during a game, although normally you'll see a sawtooth pattern as it pays out every year.

Definitely worth reproducing the moment the money was taken if you can.

**Comment by longtomjr** [comment]
So I tested this for a couple of years from my save and were unable to reproduce it. That probably means that it were something unexpected, but also means that there is no way for us to debug it. I am closing the issue for now, and if it happens again I will open it back up with the save.
